### ISSUE TITLE
Assertion failed: No voices available to provided a prioritized list.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-suite-common#33]
I’ve done a pull-all. When I try to run number-play or number-compare from phetmarks, it fails with:

> assert.js:28 Uncaught Error: Assertion failed: No voices available to provided a prioritized list.
    at window.assertions.assertFunction (assert.js:28:13)
    at NumberSuiteCommonSpeechSynthesisAnnouncer.getPrioritizedVoices (SpeechSynthesisAnnouncer.ts:489:15)
    at NumberSuiteCommonSpeechSynthesisAnnouncer.updateVoice (NumberSuiteCommonSpeechSynthesisAnnouncer.ts:60:47)
    at NumberSuiteCommonSpeechSynthesisAnnouncer.ts:44:14
    at TinyProperty.emit (TinyEmitter.ts:95:9)
    at BooleanProperty._notifyListeners (ReadOnlyProperty.ts:311:23)
    at BooleanProperty.unguardedSet (ReadOnlyProperty.ts:262:14)
    at BooleanProperty.set (ReadOnlyProperty.ts:246:12)
    at set value [as value] (Property.ts:54:11)
    at NumberSuiteCommonSpeechSynthesisAnnouncer.initialize (SpeechSynthesisAnnouncer.ts:381:37)

If I press the continue button TWICE in Chrome, the sim continues to run. But I'm not sure what the state the sim is in, and whether it's safe to continue doing development in this state.

**Comment by jessegreenberg** [comment]
Sorry about that! I must have failed to test a commit in https://github.com/phetsims/number-play/issues/204. Fixed with the above commit.

**Comment by pixelzoom** [comment]
Confirmed that number-play and number-compare now start without error in master. Closing.
